backend:
  name: git-gateway
  branch: develop

media_folder: static/img
public_folder: /img

collections:
  - label: "Kategórie - dezerty"
    name: "dessertCategories"
    folder: "src/data/dessertsfolder"
    format: json
    create: true
    fields:
      - { label: "Názov kategórie", name: title, widget: "string" }
      - { label: "Link", name: to, widget: "string" }
      - {
          label: "Produkty",
          name: products,
          widget: "list",
          allow_add: true,
          fields:
            [
              { label: "Názov", name: title, widget: "string" },
              {
                label: "Sezónne",
                name: isSeasonal,
                widget: "boolean",
                default: false,
              },
              { label: "Váha", name: weight, widget: string },
              {
                label: "Pôvodná cena",
                name: oldPrice,
                widget: "string",
                required: false,
              },
              { label: "Nová cena", name: price, widget: string },
              {
                label: "Popis Produktu",
                name: description,
                widget: string,
                required: false,
              },
              {
                label: "Obrázky",
                name: images,
                widget: list,
                allow_add: true,
                fields: [{ label: "Obrázok", name: image, widget: image }],
              },
              { label: "Link", name: to, widget: "string" },
            ],
        }
  - label: "Kategórie - Candy bar"
    name: "candyBarCategories"
    folder: "src/data/candybar"
    format: json
    create: true
    fields:
      - { label: "Názov Kategórie", name: title, widget: "string" }
      - { label: "Link", name: to, widget: "string" }
      - {
          label: "Produkty",
          name: products,
          widget: "list",
          allow_add: true,
          fields:
            [
              { label: "Názov produktu", name: title, widget: "string" },
              {
                label: "Sezónne",
                name: isSeasonal,
                widget: "boolean",
                default: false,
              },
              {
                label: "Info Kartičky",
                name: infoCards,
                required: false,
                widget: list,
                allow_add: true,
                fields:
                  [
                    {
                      label: "Kartička",
                      name: infoCard,
                      widget: "object",
                      fields:
                        [
                          {
                            label: "Popisok",
                            name: description,
                            widget: "string",
                          },
                          { label: "Cena", name: price, widget: "string" },
                          { label: "Váha", name": weight, widget: "string" },
                        ],
                    },
                  ],
              },
              {
                label: "Popis Produktu",
                name: description,
                widget: string,
                required: false,
              },
              {
                label: "Príchute",
                name: flavor,
                required: false,
                widget: list,
                allow_add: true,
                fields: [{ label: "Príchuť", name: flavor, widget: string }],
              },
              {
                label: "Obrázky",
                name: images,
                widget: list,
                allow_add: true,
                fields: [{ label: "Obrázok", name: image, widget: image }],
              },
              { label: "Link", name: to, widget: "string" },
            ],
        }
  - label: "Galéria"
    name: "gallery"
    # TODO: Remove this after the gallery has been created
    create: true
    files:
      - label: "Galéria"
        name: "gallery"
        file: "src/data/cmsGallery.json"
        fields:
          - {
              label: "Obrázky galérie",
              name: galleryImages,
              widget: list,
              allow_add: true,
              fields:
                [
                  { label: "Názov", name: "title", widget: string },
                  { label: "Obrázok", name: "image", widget: image },
                ],
          }
