backend:
  name: git-gateway

media_folder: static/img
public_folder: /img

collections:
  - label: "Dezerty"
    name: desserts
    create: true
    files:
      - label: "Dezerty - Kategórie"
        name: dessertCategories
        file: "src/data/desserts.json"
        allow_add: true
        widget: list
        fields:
          - {
              label: "Položky jídelníčku",
              name: eatmenuCollection,
              widget: list,
              fields:
                [
                  { label: "Název", name: "name", widget: string },
                  { label: "Popisek", name: "description", widget: text },
                  { label: "Cena", name: "price", widget: number },
                ],
            }
