backend:
  name: git-gateway
  branch: develop

media_folder: static/img
public_folder: /img

collections:
  - label: "Kategórie - dezerty"
    name: "dessertCategories"
    folder: "src/data/dessertsfolder"
    format: json
    create: true
    fields:
      - { label: "Title", name: title, widget: "string" }
      - { label: "Link", name: to, widget: "string" }
      - {
          label: "Produkty",
          name: products,
          widget: "list",
          allow_add: true,
          fields:
            [
              { label: "Názov", name: title, widget: "string" },
              {
                label: "Sezónne",
                name: isSeasonal,
                widget: "boolean",
                default: false,
              },
              { label: "Váha", name: weight, widget: string },
              {
                label: "Pôvodná cena",
                name: oldPrice,
                widget: "string",
                required: false,
              },
              { label: "Nová cena", name: price, widget: string },
              {
                label: "Popis Produktu",
                name: description,
                widget: string,
                required: false,
              },
              {
                label: "Obrázky",
                name: images,
                widget: list,
                allow_add: true,
                fields: [{ label: "Obrázok", name: image, widget: image }],
              },
              { label: "Link", name: to, widget: "string" },
            ],
        }
  - label: "Galéria"
    name: gallery
    create: true
    files:
      - label: "Obrázky"
        name: galleryImages
        file: "src/data/gallery.json"
        allow_add: true
        widget: list
        fields:
          - { label: "Obrázok", name: image, widget: image }
