backend:
  name: git-gateway

media_folder: static/img
public_folder: /img

collections:
  - label: "Kategórie - dezerty"
    name: "dessertCategories"
    folder: "src/data/dessertsfolder"
    format: json
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
